version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-desafio-ibm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banco_ibm
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql-ibm-desafio
    ports:
      - "3306:3306"
      - "33060:33060"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-desafio-ibm
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banco_ibm
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
