version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: banco_ibm
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql-ibm
    ports:
      - "3306:3306"
      - "33060:33060"
volumes:
  mysql_data:
    driver: local
